sonar.projectKey=ai-devsecops-demo
sonar.projectName=AI DevSecOps Demo
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=target/**,reports/**,infra/**
sonar.test.exclusions=src/test/**
sonar.coverage.exclusions=src/main/java/**/DevSecOpsDemoApplication.java,src/main/java/**/model/**
sonar.qualitygate.wait=false
