apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-devsecops-demo-config
  namespace: ai-devsecops
data:
  SERVER_PORT: "8080"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_DRIVER: "org.postgresql.Driver"
